FROM apache/airflow:2.10.5-python3.12
COPY --chown=airflow:root pyproject.toml /opt/airflow/project/pyproject.toml
COPY --chown=airflow:root src /opt/airflow/project/src
RUN python -m venv /opt/airflow/pipeline-venv && \
    PIP_USER=false /opt/airflow/pipeline-venv/bin/pip install --no-cache-dir /opt/airflow/project
