import hashlib
import logging
from dataclasses import dataclass
from datetime import UTC, date, datetime

import numpy as np
import pandas as pd
import requests
from sqlalchemy import create_engine, text
from sqlalchemy.engine import Engine
from tenacity import retry, stop_after_attempt, wait_exponential

LOG = logging.getLogger(__name__)
LOCATIONS = {"Berlin": (52.52, 13.41), "Hamburg": (53.55, 9.99), "Munich": (48.14, 11.58)}


@dataclass(frozen=True)
class RunResult:
    run_id: str
    rows: int
    rejected: int


@retry(stop=stop_after_attempt(3), wait=wait_exponential(min=1, max=8), reraise=True)
def extract(location: str, start: date, end: date) -> dict:
    if location not in LOCATIONS or start > end:
        raise ValueError("Unsupported location or reversed date range")
    lat, lon = LOCATIONS[location]
    response = requests.get(
        "https://archive-api.open-meteo.com/v1/archive",
        params={
            "latitude": lat,
            "longitude": lon,
            "start_date": start.isoformat(),
            "end_date": end.isoformat(),
            "daily": "temperature_2m_mean,precipitation_sum,wind_speed_10m_max",
            "timezone": "Europe/Berlin",
        },
        timeout=30,
    )
    response.raise_for_status()
    return response.json()


def normalize(payload: dict, location: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    daily = payload.get("daily", {})
    required = {"time", "temperature_2m_mean", "precipitation_sum", "wind_speed_10m_max"}
    if not required.issubset(daily):
        raise ValueError(f"Missing fields: {sorted(required - set(daily))}")
    frame = pd.DataFrame({key: daily[key] for key in required}).rename(
        columns={"time": "observed_on"}
    )
    frame["location"] = location
    frame["observed_on"] = pd.to_datetime(frame["observed_on"], errors="coerce").dt.date
    numeric = ["temperature_2m_mean", "precipitation_sum", "wind_speed_10m_max"]
    frame[numeric] = (
        frame[numeric].apply(pd.to_numeric, errors="coerce").replace([np.inf, -np.inf], np.nan)
    )
    invalid = frame[
        frame[["temperature_2m_mean", "precipitation_sum", "wind_speed_10m_max"]].isna().any(axis=1)
        | frame["observed_on"].isna()
        | (frame["wind_speed_10m_max"] < 0)
        | (frame["precipitation_sum"] < 0)
    ]
    clean = frame.drop(invalid.index).copy()
    clean["is_temperature_anomaly"] = (
        clean["temperature_2m_mean"] - clean["temperature_2m_mean"].mean()
    ).abs() > 2 * clean["temperature_2m_mean"].std(ddof=0)
    return clean, invalid


def load(frame: pd.DataFrame, engine: Engine) -> None:
    with engine.begin() as conn:
        for row in frame.to_dict("records"):
            row["observed_on"] = row["observed_on"].isoformat()
            conn.execute(
                text(
                    """INSERT INTO analytics_weather(location,observed_on,temperature_mean,precipitation_sum,wind_speed_max,is_temperature_anomaly) VALUES(:location,:observed_on,:temperature_2m_mean,:precipitation_sum,:wind_speed_10m_max,:is_temperature_anomaly) ON CONFLICT(location,observed_on) DO UPDATE SET temperature_mean=excluded.temperature_mean,precipitation_sum=excluded.precipitation_sum,wind_speed_max=excluded.wind_speed_max,is_temperature_anomaly=excluded.is_temperature_anomaly"""
                ),
                row,
            )


def run(
    database_url: str, location: str, start: date, end: date, payload: dict | None = None
) -> RunResult:
    if location not in LOCATIONS or start > end:
        raise ValueError("Unsupported location or reversed date range")
    engine = create_engine(database_url)
    identity = (
        "INTEGER PRIMARY KEY"
        if database_url.startswith("sqlite")
        else "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    )
    schema = f"""CREATE TABLE IF NOT EXISTS analytics_weather(id {identity},location VARCHAR(80) NOT NULL,observed_on DATE NOT NULL,temperature_mean FLOAT NOT NULL,precipitation_sum FLOAT NOT NULL,wind_speed_max FLOAT NOT NULL,is_temperature_anomaly BOOLEAN NOT NULL,UNIQUE(location,observed_on)); CREATE TABLE IF NOT EXISTS pipeline_runs(run_id VARCHAR(64) PRIMARY KEY,status VARCHAR(20),row_count INTEGER,rejected_count INTEGER,started_at TIMESTAMP,finished_at TIMESTAMP,error TEXT)"""
    with engine.begin() as conn:
        for statement in schema.split(";"):
            if statement.strip():
                conn.execute(text(statement))
    run_id = hashlib.sha256(f"{location}:{start}:{end}".encode()).hexdigest()[:24]
    started = datetime.now(UTC)
    try:
        raw = payload if payload is not None else extract(location, start, end)
        clean, rejected = normalize(raw, location)
        outside = (clean["observed_on"] < start) | (clean["observed_on"] > end)
        rejected = pd.concat([rejected, clean[outside]], ignore_index=True)
        clean = clean[~outside].copy()
        if clean.empty:
            raise ValueError("No valid observations in the requested date range")
        load(clean, engine)
        with engine.begin() as conn:
            conn.execute(
                text(
                    "INSERT INTO pipeline_runs(run_id,status,row_count,rejected_count,started_at,finished_at,error) VALUES(:id,'SUCCESS',:rows,:rejected,:started,:finished,NULL) ON CONFLICT(run_id) DO UPDATE SET status='SUCCESS',started_at=:started,row_count=:rows,rejected_count=:rejected,finished_at=:finished,error=NULL"
                ),
                {
                    "id": run_id,
                    "rows": len(clean),
                    "rejected": len(rejected),
                    "started": started.isoformat(),
                    "finished": datetime.now(UTC).isoformat(),
                },
            )
        LOG.info(
            "pipeline_completed run_id=%s rows=%s rejected=%s", run_id, len(clean), len(rejected)
        )
        return RunResult(run_id, len(clean), len(rejected))
    except Exception as exc:
        LOG.exception("pipeline_failed", extra={"run_id": run_id})
        with engine.begin() as conn:
            conn.execute(
                text(
                    "INSERT INTO pipeline_runs(run_id,status,row_count,rejected_count,started_at,finished_at,error) VALUES(:id,'FAILED',0,0,:started,:finished,:error) ON CONFLICT(run_id) DO UPDATE SET status='FAILED',row_count=0,rejected_count=0,started_at=:started,finished_at=:finished,error=:error"
                ),
                {
                    "id": run_id,
                    "started": started.isoformat(),
                    "finished": datetime.now(UTC).isoformat(),
                    "error": str(exc)[:1000],
                },
            )
        raise
    finally:
        engine.dispose()
